### ISSUE TITLE
size mismatch on visualization

### ISSUE THREAD

**Issue by nies14** [happyvictor008/HIgh-order-GCNII#1]
size mismatch for gconv_input.gconv.W: copying a param with shape torch.Size([4, 2, 64]) from checkpoint, the shape in current model is torch.Size([4, 2, 96]). I'm using ckpt_best.pth.tar as the checkpoint.

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/hgcn/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/envs/hgcn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.vscode/extensions/ms-python.python-2021.10.1336267007/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/user/.vscode/extensions/ms-python.python-2021.10.1336267007/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/user/.vscode/extensions/ms-python.python-2021.10.1336267007/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/user/anaconda3/envs/hgcn/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/user/anaconda3/envs/hgcn/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/user/anaconda3/envs/hgcn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/Desktop/Research/Higher-Order-Pose-Estimation/viz.py", line 189, in <module>
    main(parse_args())
  File "/home/user/Desktop/Research/Higher-Order-Pose-Estimation/viz.py", line 103, in main
    model_pos.load_state_dict(ckpt['state_dict'])
  File "/home/user/anaconda3/envs/hgcn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1487, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for HGCNII:
        size mismatch for gconv_input.gconv.W: copying a param with shape torch.Size([4, 2, 64]) from checkpoint, the shape in current model is torch.Size([4, 2, 96]).
        size mismatch for gconv_input.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_input.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_input.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_input.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_input.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_input.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv1.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv1.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv1.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv1.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv1.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv1.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv1.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv2.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv2.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv2.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv2.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv2.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv2.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv2.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv3.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv3.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv3.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv3.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv3.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv3.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv3.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv4.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv4.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv4.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv4.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv4.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv4.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv4.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv5.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv5.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv5.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv5.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv5.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv5.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv5.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv6.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv6.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv6.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv6.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv6.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv6.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv6.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv7.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv7.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv7.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv7.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv7.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv7.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv7.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv8.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv8.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv8.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv8.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv8.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv8.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv8.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv9.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv9.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv9.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv9.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv9.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv9.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv9.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv10.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv10.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv10.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv10.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv10.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv10.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv10.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv11.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv11.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv11.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv11.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv11.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv11.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv11.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv12.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv12.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv12.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv12.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv12.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv12.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv12.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv13.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv13.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv13.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv13.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv13.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv13.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv13.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv14.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv14.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv14.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv14.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv14.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv14.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv14.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv15.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv15.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv15.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv15.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv15.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv15.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv15.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv16.gconv.W: copying a param with shape torch.Size([4, 256, 64]) from checkpoint, the shape in current model is torch.Size([4, 384, 96]).
        size mismatch for gconv_layers.gconv16.gconv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv16.gconv.bias_2: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([96]).
        size mismatch for gconv_layers.gconv16.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv16.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv16.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_layers.gconv16.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([384]).
        size mismatch for gconv_output.W: copying a param with shape torch.Size([4, 256, 3]) from checkpoint, the shape in current model is torch.Size([4, 384, 3]).

**Comment by happyvictor008** [comment]
Hello,

There is an option of choosing hidden layer size in line 45 in main_gcn.py
If you are using pre-trained model, remember to use --hid_dim 96 or --hid_dim 64

Regards,

**Comment by nies14** [comment]
Thanks. The issue is resolved.
